import { RULES, ALIASES, PERCENT_ATTRS } from './rules.js';

function normalizeText(text) {
  return String(text || '').replace(/[Ｏ〇○Oo]/g, '0').replace(/[ＩIl丨|]/g, '1').replace(/[，,]/g, '.').replace(/[．·•]/g, '.').replace(/[％﹪]/g, '%').replace(/\s+/g, '');
}
function cleanText(text) { return String(text || '').replace(/[+✦★☆◆◇·•]/g, ' ').replace(/\s+/g, ' ').trim(); }
function levenshtein(a, b) { const x=[...a],y=[...b],dp=Array.from({length:x.length+1},()=>Array(y.length+1).fill(0)); for(let i=0;i<=x.length;i++)dp[i][0]=i; for(let j=0;j<=y.length;j++)dp[0][j]=j; for(let i=1;i<=x.length;i++)for(let j=1;j<=y.length;j++)dp[i][j]=Math.min(dp[i-1][j]+1,dp[i][j-1]+1,dp[i-1][j-1]+(x[i-1]===y[j-1]?0:1)); return dp[x.length][y.length]; }
function similarity(a,b){const x=normalizeText(a),y=normalizeText(b);if(!x||!y)return 0;if(x.includes(y)||y.includes(x))return Math.min(x.length,y.length)/Math.max(x.length,y.length)*.3+.7;return 1-levenshtein(x,y)/Math.max(x.length,y.length)}
function matchAttribute(text){const raw=cleanText(text).replace(/\s+/g,'');const patterns=[[/共[鸣鳴].*解放/,'共鸣解放伤害加成'],[/共[鸣鳴].*技能/,'共鸣技能伤害加成'],[/共[鸣鳴].*[效敩][率串宰]/,'共鸣效率'],[/普攻/,'普攻伤害加成'],[/重[击擊]/,'重击伤害加成'],[/暴[击擊].*[伤傷损損書]/,'暴击伤害'],[/暴[击擊]/,'暴击'],[/防[御禦].*(百分|%)/,'防御百分比'],[/攻[击擊].*(百分|%)/,'攻击百分比'],[/生命.*(百分|%)/,'生命百分比']];for(const[pattern,name]of patterns)if(pattern.test(raw))return{name,score:.99};let best=null;for(const[name,aliases]of Object.entries(ALIASES))for(const alias of aliases){const score=similarity(raw,alias);if(!best||score>best.score)best={name,score}}return best&&best.score>=.42?best:null}
function extractNumbers(text){return(normalizeText(text).match(/\d{1,4}(?:\.\d{1,2})?%?/g)||[]).map(raw=>({raw,numeric:Number.parseFloat(raw.replace('%','')),hasPercent:raw.includes('%')||raw.includes('.')})).filter(item=>Number.isFinite(item.numeric))}
function normalizeAttributeByValue(attribute,number){if(!number)return attribute;if(attribute==='生命'&&number.hasPercent)return'生命百分比';if(attribute==='防御'&&number.hasPercent)return'防御百分比';if(attribute==='攻击'&&number.hasPercent)return'攻击百分比';if(attribute==='生命百分比'&&!number.hasPercent&&number.numeric>=100)return'生命';if(attribute==='防御百分比'&&!number.hasPercent&&number.numeric>=30)return'防御';if(attribute==='攻击百分比'&&!number.hasPercent&&number.numeric>=25)return'攻击';return attribute}
function matchValue(attribute,number){const rule=RULES[attribute];if(!rule||!number)return null;const shouldPercent=PERCENT_ATTRS.has(attribute);let best=null;for(const value of rule.values){const isPercent=value.includes('%');if(isPercent!==shouldPercent)continue;const numeric=Number.parseFloat(value.replace('%','')),distance=Math.abs(numeric-number.numeric);if(!best||distance<best.distance)best={value,distance}}if(!best)return null;const exact=best.distance<.001,limit=shouldPercent?.16:2.1;if(!exact&&best.distance>limit)return null;return{...best,exact}}
function polygonBox(poly){if(!Array.isArray(poly))return null;const points=poly.filter(p=>Array.isArray(p)&&p.length>=2).map(p=>[Number(p[0]),Number(p[1])]).filter(p=>p.every(Number.isFinite));if(!points.length)return null;const xs=points.map(p=>p[0]),ys=points.map(p=>p[1]),minX=Math.min(...xs),maxX=Math.max(...xs),minY=Math.min(...ys),maxY=Math.max(...ys);return{minX,maxX,minY,maxY,centerY:(minY+maxY)/2,height:Math.max(1,maxY-minY)}}
function median(values){if(!values.length)return 18;const sorted=[...values].sort((a,b)=>a-b),mid=Math.floor(sorted.length/2);return sorted.length%2?sorted[mid]:(sorted[mid-1]+sorted[mid])/2}
function groupOcrRows(items){const boxes=items.map((item,index)=>{const box=polygonBox(item.poly);return box?{index,text:cleanText(item.text),score:Number(item.score)||0,...box}:null}).filter(item=>item&&item.text);const threshold=Math.max(9,median(boxes.map(b=>b.height))*.62);boxes.sort((a,b)=>a.centerY-b.centerY||a.minX-b.minX);const groups=[];for(const box of boxes){let group=groups.find(g=>Math.abs(g.centerY-box.centerY)<=threshold);if(!group){group={items:[],centerY:box.centerY};groups.push(group)}group.items.push(box);group.centerY=group.items.reduce((sum,item)=>sum+item.centerY,0)/group.items.length}return groups.map(group=>{group.items.sort((a,b)=>a.minX-b.minX);return{text:group.items.map(item=>item.text).join(' '),score:group.items.reduce((sum,item)=>sum+item.score,0)/group.items.length,centerY:group.centerY,items:group.items}}).sort((a,b)=>a.centerY-b.centerY)}
function parseOcrLine(line){const attr=matchAttribute(line.text);if(!attr)return null;const numbers=extractNumbers(line.text);if(!numbers.length)return null;let best=null;for(const number of numbers){const normalizedAttr=normalizeAttributeByValue(attr.name,number),value=matchValue(normalizedAttr,number);if(!value)continue;const confidenceScore=attr.score*.46+line.score*.24+(value.exact?.30:.17),candidate={attribute:normalizedAttr,value:value.value,confidenceScore,confidence:confidenceScore>=.76&&value.exact?'high':'medium',sourceText:line.text,y:line.centerY,ocrScore:line.score,exactValue:value.exact};if(!best||candidate.confidenceScore>best.confidenceScore)best=candidate}return best}
function loosePairCandidates(items){const boxes=items.map((item,index)=>{const box=polygonBox(item.poly);return box?{index,text:cleanText(item.text),score:Number(item.score)||0,...box,minX:box.minX,maxX:box.maxX}:null}).filter(Boolean),attrs=boxes.map(box=>({box,match:matchAttribute(box.text)})).filter(item=>item.match),numbers=boxes.filter(box=>extractNumbers(box.text).length),output=[];for(const{box:attr}of attrs){const candidates=numbers.filter(number=>number.index!==attr.index&&number.minX>=attr.minX&&Math.abs(number.centerY-attr.centerY)<=Math.max(22,Math.max(number.height,attr.height)*1.15)).sort((a,b)=>{const ay=Math.abs(a.centerY-attr.centerY),by=Math.abs(b.centerY-attr.centerY);if(ay!==by)return ay-by;return a.minX-b.minX});for(const number of candidates.slice(0,2)){const parsed=parseOcrLine({text:`${attr.text} ${number.text}`,score:(attr.score+number.score)/2,centerY:(attr.centerY+number.centerY)/2,items:[attr,number]});if(parsed)output.push(parsed)}}return output}
function chooseBestFive(candidates){const deduped=[];for(const candidate of candidates.sort((a,b)=>a.y-b.y||b.confidenceScore-a.confidenceScore)){const same=deduped.find(row=>row.attribute===candidate.attribute&&row.value===candidate.value&&Math.abs(row.y-candidate.y)<18);if(!same)deduped.push({...candidate});else if(candidate.confidenceScore>same.confidenceScore)Object.assign(same,candidate)}if(deduped.length<=5)return deduped.sort((a,b)=>a.y-b.y);let best=null;const pick=(start,chosen)=>{if(chosen.length===5){const rows=[...chosen].sort((a,b)=>a.y-b.y),unique=new Set(rows.map(row=>row.attribute)).size,gaps=rows.slice(1).map((row,i)=>row.y-rows[i].y).filter(gap=>gap>0),mean=gaps.reduce((sum,gap)=>sum+gap,0)/Math.max(1,gaps.length),variance=gaps.reduce((sum,gap)=>sum+(gap-mean)**2,0)/Math.max(1,gaps.length),spacingPenalty=mean?Math.sqrt(variance)/mean:1,confidence=rows.reduce((sum,row)=>sum+row.confidenceScore,0),lowerBonus=rows.reduce((sum,row)=>sum+row.y,0)/rows.length*.0008,score=confidence+unique*1.4-(5-unique)*3-spacingPenalty*1.1+lowerBonus;if(!best||score>best.score)best={score,rows};return}for(let i=start;i<=deduped.length-(5-chosen.length);i+=1)pick(i+1,[...chosen,deduped[i]])};pick(0,[]);return best?.rows||deduped.slice(-5)}
export function selectOcrRows(items){const groupedRows=groupOcrRows(items),parsed=groupedRows.map(parseOcrLine).filter(Boolean),loose=loosePairCandidates(items),selected=chooseBestFive([...parsed,...loose]);return{groupedRows,parsed:[...parsed,...loose],selected}}
export function ocrDetails(items,parsed,metrics){const lines=[`检测到 ${items.length} 个文字框`];if(metrics)lines.push(`检测 ${Math.round(metrics.detMs||0)} ms · 识别 ${Math.round(metrics.recMs||0)} ms · 合计 ${Math.round(metrics.totalMs||0)} ms`);lines.push('','按纵向位置整理：');parsed.groupedRows.forEach(row=>lines.push(`${Math.round(row.centerY).toString().padStart(4,' ')}  ${row.text}  [${(row.score*100).toFixed(0)}%]`));lines.push('','进入下拉框：');parsed.selected.forEach((row,i)=>lines.push(`${i+1}. ${row.attribute} ${row.value}  ← ${row.sourceText}`));return lines.join('\n')}
